### ISSUE TITLE
Include Linux arm64 binaries in releases

### ISSUE THREAD

**Issue by linuxkd** [projectdiscovery/naabu#1265]
I realize I am probably in the minority here, but I would really appreciate the inclusion of Linux arm64 binaries in the releases. I leverage multiple projectdiscovery tools, including naabu via cloud services such as AWS lambda or ECS.

To save on bloat in my container images, I pull your binary releases instead of building with go. Many of the other projectdiscovery tools already have a Linux ARM64 binary in their releases, but Naabu does not.

Thanks for your consideration!

**Comment by JoshuaProvoste** [comment]
Hi, same here. Please, consider Linux arm64 binaries in the releases, remember, they are a lot of people using Raspberry, for example.

Thanks for your time and efforts, you are a really cool team!

Best!

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @linuxkd , we'll take a look into this!

**Comment by dogancanbakir** [comment]
Thanks for opening the issue. There are some concerns about CGO support for ARM devices. We have decided to remove support for arm64 due to compatibility issues. As an alternative solution, we recommend using `go install` directly on your ARM device or considering using QEMU/Docker. These options should provide a more reliable experience. So, closing this. Feel free to reopen if you have any other questions.
