### ISSUE TITLE
Naabu latest version full port scan speed issue

### ISSUE THREAD

**Issue by Splint3r7** [projectdiscovery/naabu#129]
I recently installed the latest version of naabu 2.0.3 and the full port scan is really slow even on VPS as well. the older version of naabu was taking approx 1.5 mins to complete a full port scan but the new version is taking almost 10 mins and sometimes more than that to complete the scan.

**To Reproduce**

1- Ran naabu with command `./naabu -p - -exclude-ports 80,443 -host test.com`

<img width="707" alt="Screenshot 2021-01-25 at 7 00 12 PM" src="https://user-images.githubusercontent.com/26146246/105716351-8347d280-5f40-11eb-84da-a9c7eae88e7b.png">

Additionally, I have tried with -rate to `100`, `1000` and others to get better results but no results so far, it still takes the same time. tried threads using `-c 60` etc as well.

Also, the previous version has been using the command `-ports full -host http://hackerone.com` which doesn't support anymore in the latest one.

Anyway, not sure what mistake I am making, hope to get some help on this one!

Thanks!

**Comment by ehsandeep** [comment]
Hey @Splint3r7, 

took some time to get back on this, but here are my observations:-

>  the older version of naabu was taking approx 1.5 mins to complete a full port scan but the new version is taking almost 10 mins and sometimes more than that to complete the scan.

so in the last stable release we dropped the default `-rate` value from `10000` to `1000` so the increased time in the scan,  you can always set it back either using config file or with flag `-rate 10000`

and here is an example scan from my local machine with ` -rate 10000` and it took **28 seconds** to complete the full port scan.

```
time naabu -p - -exclude-ports 80,443 -host example.com -rate 10000

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/ v2.0.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Running SYN scan with root privileges
[INF] Found 1 ports on host example.com (93.184.216.34)
example.com:25

real	0m28.430s
user	0m2.021s
sys	0m2.024s
```

> Additionally, I have tried with -rate to 100, 1000 and others to get better results but no results so far, it still takes the same time. tried threads using -c 60 etc as well.

I tried with `-rate 5000`, half of the previous scan, and the scan time increased by 2x, which confirms the rate is working as expected.

```
time naabu -p - -exclude-ports 80,443 -host example.com -rate 5000 -silent
example.com:25

real	0m54.621s
user	0m2.730s
sys	0m3.968s
```

> Also, the previous version has been using the command -ports full -host http://hackerone.com which doesn't support anymore in the latest one.

`-ports` flag is replaced with `p` flag, and for full port scanning we can use `-p -`

let me know if you any more questions around this otherwise we can close this issue.

**Comment by Splint3r7** [comment]
@ehsandeep thanks for verifying, I'll re-test this and will get back to you!

**Comment by Splint3r7** [comment]
Thanks @ehsandeep it's working as expected.

Closing this issue.
