### ISSUE TITLE
exiting , you must be a privilaged user to run this scan

### ISSUE THREAD

**Issue by balook** [projectdiscovery/naabu#26]
exiting , you must be a privilaged user to run this scan

after this i used like sudo naabu but giving naabu didnt found

**Comment by bauthard** [comment]
Hey!

Can you please include a screenshot of the error with both commands?

**Comment by balook** [comment]
![root](https://user-images.githubusercontent.com/36122758/81663711-85264000-945c-11ea-8c0b-f3ff160f4d24.png)
![user](https://user-images.githubusercontent.com/36122758/81663719-86576d00-945c-11ea-8df8-42c4770b51cf.png)

**Comment by balook** [comment]
it asking sudo permissions every time
im using kali latest versoin ...!
even i run ```sudo naabu -host google.com``` its not rujning 
but if i run on root host like root@host~# naabu  -host google.com its workign

**Comment by bauthard** [comment]
Can you confirm if it's only issue with the localhost?

**Comment by balook** [comment]
no its not only issue with local host if i use any domain als oits giving same error

**Comment by balook** [comment]
try it from fyour side on kali .....other than root user

**Comment by Bibek1Shah** [comment]
i got the same error in my ubuntu

**Comment by nagarajcruze** [comment]
i'm also getting the same error, it asks for root privilage, even i'm running sudo echo "hello.com" | naabu , still it throws the same error :(.
![naabu](https://user-images.githubusercontent.com/32562272/82634820-6d00ae80-9c1c-11ea-8f52-9bf660224989.png)

**Comment by bauthard** [comment]
Hi @balook @Bibek1Shah @nagarajcruze, 

Try to run as the root user, not adding sudo at the start, to go into root mode, use the following command. 

```
sudo su -
```

it will ask you for your root password if you are not logged in as root, and once you in as root, you can run the binary, let me know if that helps.

**Comment by nagarajcruze** [comment]
Thanks for your response, @balook but to run port scanning sudo is enough, right? i can't log in as root user to run a tool, if possible can you update your code to run the tool with "sudo naabu" then it will be little bit easy, right?

**Comment by bauthard** [comment]
Thanks for the feedback @nagarajcruze, I will try to reproduce this behavior on my side and see how we can make it more convenient to use.

**Comment by nagarajcruze** [comment]
@bauthard wow, thankyou so much bro. waiting for the update.

**Comment by balook** [comment]
Not actually when I use sudo also its not working...the only way is...I
need to ......login as root user

**Comment by zealsham** [comment]
hey guys, you should try fixing this , login in as a root user to just to run a tool is ridiculous

**Comment by Mzack9999** [comment]
This will be addressed within next days

**Comment by Mzack9999** [comment]
Finally I got some time to look into this, and it seems like the tool has no issues, as currently pcap is used under the hood to handle the high rate of incoming packets, and it requires root privileges.

@zealsham I don't understand why it's ridiculous, as you may note also tcpdump requires to be run in a root environment in order to use pcap on any network interface, the suggestion to login as root was to avoid any kind of environment configuration issues, as it's the case in this github issue.

@balook apparently it's not working because environment paths of your root user aren't set properly, my bet is that you installed via go modules under the current user, therefore the command is not found as root, if you could post the full command while running it towards a target which is not localhost using sudo I can try to help you figure out the problem.

@nagarajcruze you are executing the `cat` command as root, not `naabu-linux-amd64` and that's the reason it complains about not having root privileges, the correct command is the following one:

```shell
$ cat live_ip.txt | sudo naabu-linux-amd64
```
