### ISSUE TITLE
[bug] privileged scan on macOS doesn't show the result

### ISSUE THREAD

**Issue by izadgot** [projectdiscovery/naabu#95]
**Environment**
macOS Catalina version 10.15.7
go 1.15.2
naabu version v2.0.2

**issue**
When I uses privileged scan (SYN scan) on macOS, naabu does not show the open port of target host. I use Wireshark to monitor packets and found that it work normally (has SYN packet send to the target host and in case that port open, target host response with SYN-ACK packet), but I not sure why naabu does not show opened port in output.

_SYN scan_
<img width="702" alt="image" src="https://user-images.githubusercontent.com/9198029/95648972-66a89b80-0b05-11eb-8ff9-48a1826db617.png">

_CONNECT scan_
<img width="713" alt="image" src="https://user-images.githubusercontent.com/9198029/95649014-9657a380-0b05-11eb-91d5-cb3b9ad802cf.png">

**Comment by fantasticpanthom** [comment]
https://superuser.com/questions/887887/different-behavior-sudo-nmap-vs-just-nmap 
According to this as a privileged user instead of TCP connect, TCP SYN stealth is used. Assuming that this is comman for all scans that run on macos , I think the reason for the results not showing up maybe that naabu syn/connect probe based scanning which cant hanlde TCP syn stealth.
